name: Server Deploy

on:
  push:
    paths:
      - 'server/**'
    branches:
      - main

jobs:
  deploy-server:
    name: Deploy Node Backend
    runs-on:  [self-hosted, server]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./server
        run: npm install

      - name: Copy Server Files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "server/*"
          target: "~/app/server"

      - name: Restart Node Server with PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pm2 delete server || true
            pm2 start ~/app/server/server.js --name server
            pm2 save
