name: Client Deploy

on:
  push:
    paths:
      - 'client/**'
    branches:
      - main

jobs:
  deploy-client:
    name: Deploy React Frontend
    runs-on: [self-hosted, server]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./client
        run: npm install

      - name: Build React App
        working-directory: ./client
        run: npm run build

      - name: Copy React Build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "client/build/*"
          target: "~/app/client/build"

      - name: Start/Restart React Frontend with PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            npm install -g serve pm2
            pm2 delete client || true
            pm2 start "serve -s ~/app/client/build -l 3000" --name client
            pm2 save
